import type { WorkflowResult, StepResult } from "../types/index.js";

/**
 * HTML Report Renderer
 *
 * WorkflowResult → 싱글 HTML 파일.
 * 의존성 0. 순수 문자열 템플릿.
 * 파트너사에 파일 하나 보내면 끝.
 */
export function renderHTMLReport(result: WorkflowResult): string {
  return `<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>EDDOps Report — ${esc(result.workflowName)}</title>
<style>${CSS}</style>
</head>
<body>
<div class="container">

  <header>
    <h1>EDDOps 실행 리포트</h1>
    <div class="meta">
      <span class="badge ${statusClass(result.status)}">${statusLabel(result.status)}</span>
      <span>${esc(result.workflowName)}</span>
      <span class="dim">Trace: ${esc(result.traceId.slice(0, 8))}...</span>
    </div>
  </header>

  <section class="summary">
    <div class="stat">
      <div class="stat-value">${(result.totalDurationMs / 1000).toFixed(1)}s</div>
      <div class="stat-label">총 시간</div>
    </div>
    <div class="stat">
      <div class="stat-value">${(result.totalTokens.input + result.totalTokens.output).toLocaleString()}</div>
      <div class="stat-label">총 토큰</div>
    </div>
    <div class="stat">
      <div class="stat-value">$${result.totalCostEstimate.toFixed(4)}</div>
      <div class="stat-label">비용 추정</div>
    </div>
    <div class="stat">
      <div class="stat-value">${result.steps.length}</div>
      <div class="stat-label">단계</div>
    </div>
  </section>

  <section class="steps">
    <h2>단계별 결과</h2>
    ${result.steps.map(renderStep).join("\n")}
  </section>

  <section class="trace-download">
    <h2>트레이스 데이터</h2>
    <button onclick="downloadTrace()">JSON 다운로드</button>
    <script>
      const traceData = ${JSON.stringify(result, null, 2)};
      function downloadTrace() {
        const blob = new Blob([JSON.stringify(traceData, null, 2)], {type: 'application/json'});
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = 'trace-${result.traceId.slice(0, 8)}.json';
        a.click();
      }
    </script>
  </section>

  <footer>
    <p class="dim">Generated by EDDOps CLI v0.1.0 — ${new Date().toISOString()}</p>
  </footer>

</div>
</body>
</html>`;
}

// ─── Step Renderer ───────────────────────────────────────────

function renderStep(step: StepResult, index: number): string {
  const icon = statusIcon(step.status);
  const tokens = step.tokenUsage.input + step.tokenUsage.output;
  const hasEval = step.evaluation !== undefined;
  const hasValidationFail = step.validation && !step.validation.passed;

  return `
    <details class="step ${step.status}" ${step.status === "failed" ? "open" : ""}>
      <summary>
        <span class="step-icon">${icon}</span>
        <span class="step-name">Step ${index + 1}: ${esc(step.stepId)}</span>
        <span class="step-meta">
          ${(step.durationMs / 1000).toFixed(1)}s
          · ${tokens.toLocaleString()} tok
          ${hasEval ? renderEvalBadge(step.evaluation!) : ""}
        </span>
        <span class="badge ${statusClass(step.status)}">${step.status}</span>
      </summary>
      <div class="step-detail">
        ${hasValidationFail ? renderValidationFailures(step) : ""}
        ${hasEval ? renderEvalDetail(step.evaluation!) : ""}
        ${renderTokenBreakdown(step)}
        ${step.output ? renderOutput(step.output) : ""}
      </div>
    </details>`;
}

function renderEvalBadge(eval_: NonNullable<StepResult["evaluation"]>): string {
  const pct = Math.round(eval_.score * 100);
  const cls = eval_.passed ? "eval-pass" : "eval-fail";
  return `<span class="eval-badge ${cls}">${eval_.score.toFixed(2)}</span>`;
}

function renderEvalDetail(eval_: NonNullable<StepResult["evaluation"]>): string {
  const pct = Math.round(eval_.score * 100);
  const barCls = eval_.passed ? "bar-pass" : "bar-fail";
  return `
    <div class="eval-detail">
      <div class="eval-header">LLM 평가 (${eval_.action})</div>
      <div class="eval-bar-container">
        <div class="eval-bar ${barCls}" style="width: ${pct}%"></div>
      </div>
      <div class="eval-score">${eval_.score.toFixed(2)} / 1.00</div>
      ${eval_.reasoning ? `<div class="eval-reasoning">${esc(eval_.reasoning)}</div>` : ""}
    </div>`;
}

function renderValidationFailures(step: StepResult): string {
  if (!step.validation?.failures.length) return "";
  return `
    <div class="validation-failures">
      <div class="fail-header">검증 실패</div>
      <ul>
        ${step.validation.failures.map((f) => `<li>${esc(f.rule.message)}</li>`).join("\n")}
      </ul>
    </div>`;
}

function renderTokenBreakdown(step: StepResult): string {
  return `
    <div class="token-breakdown">
      <table>
        <tr><th>Input</th><td>${step.tokenUsage.input.toLocaleString()}</td></tr>
        <tr><th>Output</th><td>${step.tokenUsage.output.toLocaleString()}</td></tr>
        <tr><th>시간</th><td>${(step.durationMs / 1000).toFixed(1)}s</td></tr>
      </table>
    </div>`;
}

function renderOutput(output: unknown): string {
  const text =
    typeof output === "string"
      ? output
      : JSON.stringify(output, null, 2);

  // 긴 출력은 접기
  const truncated = text.length > 2000;
  const display = truncated ? text.slice(0, 2000) + "\n\n... (truncated)" : text;

  return `
    <div class="output">
      <div class="output-header">출력 ${truncated ? `(${text.length.toLocaleString()}자 중 2,000자)` : ""}</div>
      <pre><code>${esc(display)}</code></pre>
    </div>`;
}

// ─── Utilities ───────────────────────────────────────────────

function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function statusIcon(status: StepResult["status"]): string {
  switch (status) {
    case "success": return "&#x2713;";
    case "flagged": return "&#x26A0;";
    case "failed": return "&#x2717;";
    case "skipped": return "&#x25CB;";
    default: return "?";
  }
}

function statusClass(status: string): string {
  switch (status) {
    case "success": return "status-success";
    case "partial":
    case "flagged": return "status-warn";
    case "failed": return "status-fail";
    default: return "status-dim";
  }
}

function statusLabel(status: string): string {
  switch (status) {
    case "success": return "SUCCESS";
    case "partial": return "PARTIAL";
    case "failed": return "FAILED";
    default: return status.toUpperCase();
  }
}

// ─── CSS ─────────────────────────────────────────────────────

const CSS = `
:root {
  --bg: #0d1117;
  --surface: #161b22;
  --border: #30363d;
  --text: #e6edf3;
  --text-dim: #7d8590;
  --green: #3fb950;
  --yellow: #d29922;
  --red: #f85149;
  --blue: #58a6ff;
  --mono: 'SF Mono', 'Cascadia Code', 'Fira Code', monospace;
  --sans: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: var(--sans);
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
}

.container {
  max-width: 900px;
  margin: 0 auto;
  padding: 2rem 1.5rem;
}

header {
  margin-bottom: 2rem;
}

header h1 {
  font-size: 1.5rem;
  font-weight: 600;
  margin-bottom: 0.5rem;
}

.meta {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  font-size: 0.875rem;
}

.dim { color: var(--text-dim); }

.badge {
  display: inline-block;
  padding: 0.125rem 0.5rem;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 600;
  font-family: var(--mono);
}

.status-success { background: #1a3a2a; color: var(--green); }
.status-warn { background: #3a2a1a; color: var(--yellow); }
.status-fail { background: #3a1a1a; color: var(--red); }
.status-dim { background: var(--surface); color: var(--text-dim); }

/* ─── Summary Stats ─── */
.summary {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 1rem;
  margin-bottom: 2rem;
}

.stat {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem;
  text-align: center;
}

.stat-value {
  font-size: 1.5rem;
  font-weight: 700;
  font-family: var(--mono);
}

.stat-label {
  font-size: 0.75rem;
  color: var(--text-dim);
  margin-top: 0.25rem;
}

/* ─── Steps ─── */
.steps h2 {
  font-size: 1rem;
  margin-bottom: 1rem;
  color: var(--text-dim);
}

.step {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  margin-bottom: 0.5rem;
  overflow: hidden;
}

.step.failed { border-color: var(--red); }
.step.flagged { border-color: var(--yellow); }

.step summary {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.75rem 1rem;
  cursor: pointer;
  font-size: 0.875rem;
  list-style: none;
}

.step summary::-webkit-details-marker { display: none; }

.step summary::before {
  content: '\\25B6';
  font-size: 0.625rem;
  transition: transform 0.2s;
  color: var(--text-dim);
}

.step[open] summary::before {
  transform: rotate(90deg);
}

.step-icon {
  font-size: 1rem;
  width: 1.25rem;
  text-align: center;
}

.step.success .step-icon { color: var(--green); }
.step.flagged .step-icon { color: var(--yellow); }
.step.failed .step-icon { color: var(--red); }
.step.skipped .step-icon { color: var(--text-dim); }

.step-name {
  font-weight: 500;
  flex: 1;
}

.step-meta {
  font-family: var(--mono);
  font-size: 0.75rem;
  color: var(--text-dim);
}

.step-detail {
  padding: 0 1rem 1rem;
  border-top: 1px solid var(--border);
}

/* ─── Eval Bar ─── */
.eval-badge {
  font-family: var(--mono);
  font-size: 0.6875rem;
  padding: 0.0625rem 0.375rem;
  border-radius: 3px;
}

.eval-pass { background: #1a3a2a; color: var(--green); }
.eval-fail { background: #3a1a1a; color: var(--red); }

.eval-detail {
  margin-top: 0.75rem;
  padding: 0.75rem;
  background: var(--bg);
  border-radius: 6px;
}

.eval-header {
  font-size: 0.75rem;
  color: var(--text-dim);
  margin-bottom: 0.5rem;
}

.eval-bar-container {
  height: 8px;
  background: var(--border);
  border-radius: 4px;
  overflow: hidden;
}

.eval-bar {
  height: 100%;
  border-radius: 4px;
  transition: width 0.3s;
}

.bar-pass { background: var(--green); }
.bar-fail { background: var(--red); }

.eval-score {
  font-family: var(--mono);
  font-size: 0.75rem;
  margin-top: 0.25rem;
  color: var(--text-dim);
}

.eval-reasoning {
  margin-top: 0.5rem;
  font-size: 0.8125rem;
  color: var(--text-dim);
  font-style: italic;
}

/* ─── Validation Failures ─── */
.validation-failures {
  margin-top: 0.75rem;
  padding: 0.75rem;
  background: #1a0a0a;
  border: 1px solid #3a1a1a;
  border-radius: 6px;
}

.fail-header {
  font-size: 0.75rem;
  color: var(--red);
  font-weight: 600;
  margin-bottom: 0.5rem;
}

.validation-failures ul {
  list-style: none;
  font-size: 0.8125rem;
}

.validation-failures li::before {
  content: '\\2717 ';
  color: var(--red);
}

/* ─── Token Breakdown ─── */
.token-breakdown {
  margin-top: 0.75rem;
}

.token-breakdown table {
  font-size: 0.75rem;
  font-family: var(--mono);
}

.token-breakdown th {
  color: var(--text-dim);
  text-align: left;
  padding-right: 1rem;
  font-weight: 400;
}

/* ─── Output ─── */
.output {
  margin-top: 0.75rem;
}

.output-header {
  font-size: 0.75rem;
  color: var(--text-dim);
  margin-bottom: 0.25rem;
}

.output pre {
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 0.75rem;
  overflow-x: auto;
  max-height: 400px;
  overflow-y: auto;
}

.output code {
  font-family: var(--mono);
  font-size: 0.8125rem;
  color: var(--text);
  white-space: pre-wrap;
  word-break: break-word;
}

/* ─── Trace Download ─── */
.trace-download {
  margin-top: 2rem;
}

.trace-download h2 {
  font-size: 1rem;
  margin-bottom: 0.75rem;
  color: var(--text-dim);
}

.trace-download button {
  background: var(--surface);
  color: var(--blue);
  border: 1px solid var(--border);
  border-radius: 6px;
  padding: 0.5rem 1rem;
  font-family: var(--sans);
  font-size: 0.875rem;
  cursor: pointer;
}

.trace-download button:hover {
  background: var(--border);
}

/* ─── Footer ─── */
footer {
  margin-top: 3rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border);
  font-size: 0.75rem;
}

/* ─── Responsive ─── */
@media (max-width: 640px) {
  .summary { grid-template-columns: repeat(2, 1fr); }
  .step summary { flex-wrap: wrap; }
  .step-meta { width: 100%; margin-top: 0.25rem; }
}
`;
